DIALOG materialImportDialog
{
  NAME DIALOG_TITLE;
  GROUP
  {
    COLUMNS 1;
    SPACE 8,8;
    BORDERSIZE 4,4,4,4;
    STATICTEXT { NAME OPEN_FOLDER; }
    FILENAME MATERIAL_DIRECTORY_PATH { DIRECTORY; }
  }
}